name: Railway
version: 0.1.0
main: org.cubexmc.railway.Railway
api-version: '1.21'
folia-supported: true
authors: ["CubeXMC"]
description: "Headway-based multi-car minecart railway plugin"

commands:
  rail:
    description: Railway admin command
    usage: "/rail <line|stop|reload>"
    permission: railway.admin
    aliases: [railway]

permissions:
  railway.admin:
    description: Allows using Railway admin commands
    default: op
  railway.use:
    description: Allows using Railway features as a player
    default: true


